name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make gcc gcovr build-essential
      - name: Build and Run Lab1
        run: |
          make -C Lab1
          ./Lab1/Lab1
      - name: Build and Run Lab2
        run: |
          make -C Lab2
          ./Lab2/Lab2
      - name: Install Renode
        run: |
          .Lab3/install_renode.sh
      - name: Build and Run Lab3
        run: |
          make run -C Lab3
