name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Code-Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment
        run: ./install_tools.sh
      - name: Run renode based code coverage analysis
        run: make coverage -C Lab3
      - name: Lab4 code coverage analysis
        run: make coverage_summary -C Lab4
